openapi: 3.0.3
components:
  schemas:
    External_Lead_Object:
      type: object
      properties:
        Id:
          type: string
        Firstname:
          type: string
        Lastname:
          type: string
        Company:
          type: string
        State:
          type: string
        Country:
          type: string
        Email:
          type: string
        source: 
          type: string
        score: 
          type: number
        created: 
          type: string
          format: date-time
        updated: 
          type: string
          format: date-time

