openapi: 3.0.3
components:
  schemas:
    patient_engagement:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        gender:
          type: string
        created: 
          type: string
          format: date-time
        bp: 
          type: number
        hr: 
          type: number
